;; ----------------------------The “Chain System”----------------------------
;;	Items:
;;		- Items represent an icon on the map.
;;		- Items have 3 states:
;;			- *False: *Reqs-not-met; icon is invisible
;;			- *Available: *Reqs met but *Needs not yet finished; icon is visible
;;			- *True: *Needs have been met; icon is set to IsFound/invisible
;;				- For most items, this state is met by the appropriate save-file value being set, which is most often just collecting the in-game item.
;;					- These links are set up in ItemFinder.json.
;;		- The only required item fields are: [int]ID, [int]CategoryID, [string]Title, [double]x, [double]y
;;		- Self explanatory fields: [int]IconID, [string]WhereAt, [string]Effect, [string]Tips, [string]*Notes, [string array]ImageURLs, [string array]OtherLinks
;;	Requirements (*Reqs) field:
;;		- Things required for the item to become available/visible.
;;		- *Reqs are made up of items. Items are separated by <strike>pluses “+”</strike> backticks “`” and pipes “|”. a`b`c|b`d means (a AND b AND c) OR (b OR d).
;;		- Items can be the following things:
;;			- *StaticID: A numeric ID key found in StaticLinks table.
;;				- Direction: North/South/East/West
;;				- Currencies: Rosary, Shard
;;				- [Misc.json] A group of item IDs
;;				- [Misc.json] A category ID
;;			- *LinkID: A numeric ID link to another item
;;			- *Unlinked: A named item that does not have (but should have) an item it is directly linked to. Preceeded by a question mark “?”.
;;				- Can contain any character except: “^” or “|” or “`”
;;		- Items can be preceeded by one or more flags in any order
;;			- Amount: An asterisk “*” followed by a number. This specifies how many of an item is needed.
;;				- If an amount is directly followed by a numeric ID without any flags after, another asterisk “*” is added to separate the numeric digits.
;;			- Recommended: An at sign “@” specifying the item is only recommended, not required
;;			- Not: An exclamation mark “!” specifyiung the requirement fails if the item is true.
;;			- Started: A tilde “~” specifying the item only needs to be started, not completed.
;;		- After the list of required items may be a caret “^” followed by a string that specifies additional information that is *Unlinked (cannot be linked to other items).
;;		- When viewing an item’s information, *Reqs are listed under “Requirements”, and the required items list it under “Unlocks”.
;;	*Needs field:
;;		- Things needed to complete the item. When these things have been completed, the save-file value should generally be set (item becomes true).
;;		- Same format as *Reqs but without the pipe “|” clause, <FlagRecommend> “@”, and certain <StaticID>s (Cardinal Directions).
;;	*Rewards:
;;		- *Rewards are what the player receives for finishing an item, generally a quest or an objective.
;;		- This field follows the same rules as the *Needs field, except:
;;			- The <FlagNot> “!” and <FlagStarted> “~” flags are not supported
;;	Stores:
;;		- An item (generally of “Vendor” category type) can have stores where they buy and sell things.
;;		- Their stores are made up of a list of transactions that have their own *Reqs, *Needs, and *Rewards.
;;	*******IMPORTANT*******: It is important to note the difference between *Reqs and *Rewards.
;;		- They can often serve the same purpose (an item can be gained either as a reward, or if its requirements are met). The major difference being when the item becomes visible on the map.
;;			- *Reqs
;;				- For example, an objective that follows another objective should be a *Req, as we don’t want it to show until the first objective is complete.
;;				- When viewing an item’s information, other items that require it are listed under “Unlocks”.
;;			- *Rewards
;;				- However, an item that a player might want to know about, for example, the “Drifter’s Cloak” for the “Flexile Spines” quest should be a *Reward, so the player can know it’s there.
;;				- *Rewards do not show up for the player until their quest/objective has its *Reqs met (configurable).
;;				- When viewing an item’s information, *Rewards are listed under “Rewards”, and the rewarded items list it under “Requirements”.
;;	“Arena Battle” *Notes:
;;		- Each section of an arena battle is on its own line and lists the spawned monsters in the format “- 5 MonsterA + 3 MonsterB + 1 MonsterC”

;; ----------------------------items.ebnf JSON format---------------------------
<FullList>		::=	"{" <Item>* "}"
<Item>			::=	<QuoteChar> <UInt> <QuoteChar> ":" "{" <ICategoryID> <ITitle> <Ix> <Iy> <IIconID>? <IReqs>? <IWhereAt>? <INeeds>? <IRewards>? <IEffect>? <ITip>? <INotes>? <IStore>? <IImageURLs>? <OtherLinks>? "}" <Comma>
<ICategoryID>	::=	<QuoteChar> "CategoryID" <QuoteChar> ":" <UInt>			<Comma>
<ITitle>		::=	<QuoteChar> "Title"		 <QuoteChar> ":" <JSString>		<Comma>
<Ix>			::=	<QuoteChar> "x"			 <QuoteChar> ":" <Float>		<Comma>
<Iy>			::=	<QuoteChar> "y"			 <QuoteChar> ":" <Float>		<Comma>
<IIconID>		::=	<QuoteChar> "IconID"	 <QuoteChar> ":" {<Digit>}{1,3}	<Comma>
<IReqs>			::=	<QuoteChar> "Reqs"		 <QuoteChar> ":" <ReqStr>		<Comma>
<IWhereAt>		::=	<QuoteChar> "WhereAt"	 <QuoteChar> ":" <JSString>		<Comma>
<INeeds>		::=	<QuoteChar> "Needs"		 <QuoteChar> ":" <NeedStr>		<Comma>
<IRewards>		::=	<QuoteChar> "Rewards"	 <QuoteChar> ":" <NeedStr>		<Comma>
<IEffect>		::=	<QuoteChar> "Effect"	 <QuoteChar> ":" <JSString>		<Comma>
<ITip>			::=	<QuoteChar> "Tip"		 <QuoteChar> ":" <JSString>		<Comma>
<INotes>		::=	<QuoteChar> "Notes"		 <QuoteChar> ":" <JSString>		<Comma>
<IStore>		::=	<QuoteChar> "Store"		 <QuoteChar> ":" "[" <StoreItem>+   "]" <Comma>
<IImageURLs>	::=	<QuoteChar> "ImageURLs"	 <QuoteChar> ":" "[" <ImageURLItem>+"]" <Comma>
<OtherLinks>	::=	<QuoteChar> "OtherLinks" <QuoteChar> ":" "[" <OtherLinkItm>+"]" <Comma>

;; -------------------------Other standardized sections-------------------------
;; For “Arena Battle”s the *Notes is in the format <ABRows>:
;;    ^((- \d+ .+?)( \+ \d+ .+?)*(\n|$))+$
<ABRows>		::=	<ABRow> { "\n" <ABRow> }*
<ABRow>			::=	"- " <ABItem> { " + " <ABItem> }*
<ABItem>		::=	<UInt> " " { character }+

;; *Need Note	: Non-Supported parts of <AndExpr>: <FlagRecommend>, certain <StaticID>s (Cardinal Directions)
;; *Rewards Note: Same as “*Need Note” except the <FlagNot> and <FlagStarted> flags are not supported
<NeedStr>		::=	<QuoteChar> <AndExpr>? <StrExtra>? <QuoteChar>

;; Array parts
<StoreItem>	::=	"{" <IReqs> <INeeds> <IRewards> "}" <Comma>
;; IImageURLItem and OtherLinkItm both expect properly escaped URLs. URLs strings are directly sent in https requests as-is
<IImageURLItem>	::=	<QuoteChar> "https://" <JSStringChar>+ <QuoteChar> <Comma>
;; URL can be followed by an optional link name (URL escape not necessary) prefixed with a pipe “|”. If not given, the URL will be the link name. The Link name will have UrlDecode() ran on it for display
<OtherLinkItm>	::=	<QuoteChar> "https://" <JSStringChar>+ { "|" <JSStringChar>+ }? <QuoteChar> <Comma>

;; ----------------------“Requirements” *Reqs string format---------------------
;;															ReqStr: *Reqs and information on where to be found. Note: Will be a <JSString>.
<ReqStr>		::=	<QuoteChar> <OrExpr>? <StrExtra>? <QuoteChar>
;;															StrExtra: Gives additional information (often *Unlinked) :: Optional; Starts with ^, followed by one or more characters.
<StrExtra>		::=	"^" { character }+
;;															OrExpr: Different ways to satisfy the requirement :: Alternatives separated by | (OR); one or more AndExpr
<OrExpr>		::=	<AndExpr> { "|" <AndExpr> }*
;;															AndExpr: Requirements that must be met together :: One or more ReqItem joined by ` (AND, higher precedence). Used to be “+” but needed to be moved to an uncommon symbol.
<AndExpr>		::=	<ReqItem> { "`" <ReqItem> }*
;;															ReqItem: Optional flags followed by name
<ReqItem>		::=	<Flags>* <ReqName>
;;															Flags: List of flags
<Flags>			::=	<FlagAmount> | <FlagNot> | <FlagStarted> | <FlagRecommend>
;;															FlagAmount: Number of the items required. Extra asterisk is required if following RegName is a <StaticID> or <LinkID>
<FlagAmount>	::=	"*" <UInt> { "*" }?
;;															FlagNot: Requirement must not be met
<FlagNot>		::=	"!"
;;															FlagStarted: Must be started (but not complete)
<FlagStarted>	::=	"~"
;;															FlagRecommend: If the item is only recommended and not required
<FlagRecommend>	::=	"@"
;;															ReqName: Static ID, Link ID, or Unlinked Name
<ReqName>		::=	<StaticID> | <LinkID> | <UnlinkedName>
;;															StaticID: A link to a StaticLinks item in StaticLinks table (Misc.json)
<StaticID>		::=	<UInt>
;;															LinkID: A link to another item in the json file.
<LinkID>		::=	<UInt>
;;															UnlinkedName: Represents an item that could be, but hasn’t, been linked, so we only have the [string]Name. One or more allowed characters (matches regex [^^|`]+)
<UnlinkedName>	::=	"?" { any character but "^" | "|" | "`" }+
;;															This represents a javascript string
<JSString>		::=	<QuoteChar> <JSStringChar>* <QuoteChar>
;;															This represents a javascript string character, which cannot be modeled in BNF
<JSStringChar>	::=	character
;;															Floating point number
<Float>			::=	"-"? { <Digit> }{1,17} "." { <Digit> }{1,17}
;;															UInt: Unsigned int number, 1–8 digits (value < 100,000,000)
<UInt>			::=	{ <Digit> }{1,8}
;;															Digit: Decimal digits
<Digit>			::=	  "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<QuoteChar>		::=	""""
<Comma>			::=	","