#!/bin/bash
#This file does nothing by itself. Run the .sh files in this directory.

#Directories
links_dir="links"
trans_dir="Translations"
plugin_dir="dakusan"
zip_dir="zip"

#Ensure links directory is set up correctly
ERRORS=0
report_error() {
	echo "Error: $1" >&2
	ERRORS=1
	return 0
}
exit_error() {
	echo "Error: $1" >&2
	exit 1
}
ensure_link() {
	local target="$1"
	local source="$2"
	#Conditional substitution for SilkDev Assets -> Internal in source
	if [[ "$source" == *"SilkDev/Assets"* ]]; then
		source="${source/SilkDev\/Assets/SilkDev\/Internal}"
	fi

	[ -e "$target" ] && [ ! -L "$target" ] && { report_error "$target exists but is not a symlink"; return 1; }
	[ -L "$target" ] || ln -s "$source" "$target" || report_error "$target failed creation"
	readlink -e "$target" >/dev/null 2>&1 || report_error "Symlink $target points to missing $(pwd)/$(dirname "$target")/$source"
}
ensure_dir() {
	local dir="$1"
	[ -e "$dir" ] && [ ! -d "$dir" ] && { report_error "$dir exists but is not a directory"; return 1; }
	mkdir -p "$dir" || report_error "$dir failed creation"
}

compile_json() {
	rm -f "$1"
	php "$ESCAPE_LINKS/WebServer/CreateJsons.php" "Build=$2&CompactJSON=1" > "$1" || report_error "$1 build failed: `cat "$1"`"
}

#Make all symlinks in the links directory
ensure_dir "$links_dir" || exit 1
cd "$links_dir"
ESCAPE_LINKS="../.."

#Ensure file symlinks
ensure_link "ItemFinder.json" "$ESCAPE_LINKS/PharloomAtlas/Assets/ItemFinder.json"
for project in NoClip PharloomAtlas PinFinder SilkDev; do
	ensure_link "$project.dll" "$ESCAPE_LINKS/$project/bin/Release/netstandard2.1/$project.dll"
	ensure_link "$project.NexusMods.txt" "$ESCAPE_LINKS/$project/Assets/$project.NexusMods.txt"
	ensure_link "$project.README.md" "$ESCAPE_LINKS/$project/README.md"
done
ensure_link "Root.README.md" "$ESCAPE_LINKS/README.md"
ensure_link "WebServer.README.md" "$ESCAPE_LINKS/WebServer/README.md"
[[ $(type -t extra_links) == function ]] && extra_links

#Ensure translation symlinks
ensure_dir "$trans_dir" || exit 1
for project in NoClip PharloomAtlas PinFinder SilkDev; do
	ensure_link "$trans_dir/$project" "../$ESCAPE_LINKS/$project/Assets/Translations"
done

#Stop here if there were any errors
(( ERRORS == 1 )) && exit 1

#Create the zip and project directories
cd ..
ensure_dir "$zip_dir" || exit 1
ensure_dir "$plugin_dir" || exit 1

#Functions used by callers to finish up the job
MakeZip() {
	#Compile the zip
	local zip_path="$zip_dir/$1"
	rm -f "$zip_path"
	cp -Lpr "$links_dir/"* "$plugin_dir/"				|| exit_error "Failed to copy $links_dir to $plugin_dir"
	rm -f "$plugin_dir/$trans_dir/"*"/default.tr.json"
	zip -r -9 "$zip_path" "${@:2}"						|| exit_error "Zipping failed"
	#7z a -t7z -mx=9 "$zip_dir/${1%.zip}.7z" "${@:2}"

	#.en zip (exclude Translations params)
	local en_zip="${zip_path%.zip}.en.zip"
	local en_args=()
	shift #Skip $1
	for arg in "$@"; do
		[[ ! "$arg" == "$plugin_dir/$trans_dir/"* ]] && en_args+=("$arg")
	done
	zip -r -9 "$en_zip" "${en_args[@]}" || exit_error "Zipping .en failed"
	#7z a -t7z -mx=9 "${en_zip%.zip}.7z" "${en_args[@]}"

	#Cleanup
	rm -rf "$plugin_dir"

	#Let the user know the results
	unzip -l "$zip_path"
	echo "Created: $zip_path"

	#Return success
	exit 0
}
AddProject() {
	echo "$plugin_dir/$1.dll" "$plugin_dir/$1.README.md" "$plugin_dir/$trans_dir/$1"
}