//This test code is 99% generated by ChatGPT and is not included in metrics. I do not trust the below code at all.
using SilkDev;
using System.Globalization;
using System.Text.RegularExpressions;

namespace UnitTests;

public sealed partial class AsyncLoggerDuplicateTests
{
	// -------------------------
	// One-liner tests
	// -------------------------

	[Fact]
	public async Task FirstOccurrence_IsWrittenAsIs() =>
		await RunCase(
			0.30, 0.10,
			[ "A", 200 ],					// single log, allow writer to flush
			[
				new PlainExp("A", 1),		// first occurrence is written normally
				new DupExp("A", 0),			// no duplicate annotation
				new SummaryExp("A", 0)		// no pause summary
			]
		);

	[Fact]
	public async Task DuplicateWithinWindow_ForcedSummary_CountsSuppressed() =>
		await RunCase(
			0.40, 0.10,
			[
				"X",
				50,
				"X",						// first duplicate → pause starts
				(2, "X"),					// suppressed duplicates during pause
				1500						// allow monitor to force summary
			],
			[
				new PlainExp("X", 1),				// first occurrence
				new DupExp("X", 1),					// one duplicate annotation
				new SummaryExp("X", 1, Repeated:2),	// forced summary with 2 suppressed
				new SummaryPlusExp("X", false)		// critical: forced path has no +1
			]
		);

	[Fact]
	public async Task NaturalSummary_WhenMessageArrivesAfterPause() =>
		await RunCase(
			0.25, 5.0,						// large force window to avoid monitor forcing
			[
				"N",
				30,
				"N",						// duplicate → pause starts
				350,						// wait past pause end
				"N",						// natural summary triggered by next log
				200
			],
			[
				new PlainExp("N", 1),				// first occurrence
				new DupExp("N", 1),					// duplicate annotation
				new SummaryExp("N", 1, Repeated:1),	// natural summary = 0 suppressed + 1
				new SummaryPlusExp("N", true)		// proves natural path (+1)
			]
		);

	[Fact]
	public async Task NotADuplicate_AfterWindow_ResetsAndWritesNormally() =>
		await RunCase(
			0.20, 0.10,
			[
				"R",
				300,						// wait past duplicate window
				"R",						// treated as new first occurrence
				200
			],
			[
				new PlainExp("R", 2),		// both logs written normally
				new DupExp("R", 0),			// no duplicate annotations
				new SummaryExp("R", 0)		// no pause summaries
			]
		);

	[Fact]
	public async Task MultipleMessages_PauseIndependently() =>
		await RunCase(
			0.35, 0.10,
			[
				"A",
				"B",
				50,
				"A",						// pause A
				"B",						// pause B
				"A",						// suppressed A
				"B",						// suppressed B
				1500						// allow forced summaries
			],
			[
				new PlainExp("A", 1),				// first A
				new PlainExp("B", 1),				// first B
				new DupExp("A", 1),					// A duplicate annotation
				new DupExp("B", 1),					// B duplicate annotation
				new SummaryExp("A", 1, Repeated:1),	// forced summary
				new SummaryExp("B", 1, Repeated:1),
				new SummaryPlusExp("A", false),
				new SummaryPlusExp("B", false)
			]
		);

	[Fact]
	public async Task Boundary_DuplicateNearWindowEnd_StillSummarizes() =>
		await RunCase(
			0.12, 0.10,
			[
				"S",
				50,						// near end of duplicate window
				"S",						// duplicate with near-zero pause
				2500						// allow natural or forced summary
			],
			[
				new SummaryAtLeastExp("S", 1)	// summary must still occur
			]
		);

	// -------------------------
	// DSL
	// -------------------------

	private abstract record Expectation;
	private sealed record PlainExp(string Message, int Count) : Expectation;
	private sealed record DupExp(string Message, int Count) : Expectation;
	private sealed record SummaryExp(string Message, int Count, int? Repeated = null) : Expectation;
	private sealed record SummaryPlusExp(string Message, bool PlusOne) : Expectation;
	private sealed record SummaryAtLeastExp(string Message, int MinCount) : Expectation;

	private enum EventKind { Plain, Duplicate, Summary }

	private sealed record LogEvent(
		EventKind Kind,
		string Message,
		double? AfterSeconds = null,
		double? PauseSeconds = null,
		double? PausedSeconds = null,
		int? RepeatedCount = null,
		bool PlusOne = false
	);

	private static async Task RunCase(double DuplicateWindowSeconds, double AfterWindowForceSeconds, object[] Actions, Expectation[] Expects)
	{
		string LogFile=CreateEmptyTempFile();

		using(AsyncLogger Logger = new(LogFile)) {
			Logger.DuplicateWindowSeconds=DuplicateWindowSeconds;
			Logger.AfterWindowForceSeconds=AfterWindowForceSeconds;

			await Task.Delay(150);  //	allow writer to initialize

			foreach(object Action in Actions) {
				if(Action is string LogLine) { Logger.Log(LogLine); continue; }
				if(Action is int WaitMs) { await Task.Delay(WaitMs); continue; }
				if(Action is (int Count, string Line)) {
					for(int i = 0; i<Count; i++)
						Logger.Log(Line);
					continue;
				}

				throw new InvalidOperationException($"Unsupported action type: {Action.GetType().FullName}");
			}

			await Task.Delay(200);  //	allow background writer to flush
		}

		string Content=File.ReadAllText(LogFile);
		AssertExpectations(ParseEvents(Content), Expects);
	}

	private static void AssertExpectations(List<LogEvent> Events, Expectation[] Expects)
	{
		foreach(Expectation Exp in Expects) {
			switch(Exp) {
				case PlainExp P:
					Assert.Equal(P.Count, CountEvents(Events, EventKind.Plain, P.Message));
					break;

				case DupExp D:
					Assert.Equal(D.Count, CountEvents(Events, EventKind.Duplicate, D.Message));
					break;

				case SummaryExp S: {
					List<LogEvent> Matches=FindEvents(Events, EventKind.Summary, S.Message);
					Assert.Equal(S.Count, Matches.Count);
					if(S.Repeated is int R)
						foreach(LogEvent E in Matches)
							Assert.Equal(R, E.RepeatedCount);
					break;
				}

				case SummaryPlusExp SP: {
					List<LogEvent> Matches=FindEvents(Events, EventKind.Summary, SP.Message);
					Assert.NotEmpty(Matches);
					foreach(LogEvent E in Matches)
						Assert.Equal(SP.PlusOne, E.PlusOne);
					break;
				}

				case SummaryAtLeastExp SA: {
					List<LogEvent> Matches=FindEvents(Events, EventKind.Summary, SA.Message);
					Assert.True(Matches.Count>=SA.MinCount);
					break;
				}

				default:
					throw new InvalidOperationException("Unknown expectation type");
			}
		}
	}

	private static int CountEvents(List<LogEvent> Events, EventKind Kind, string Message) =>
		Events.Count(e => e.Kind==Kind && StringComparer.Ordinal.Equals(e.Message, Message));

	private static List<LogEvent> FindEvents(List<LogEvent> Events, EventKind Kind, string Message) =>
		[.. Events.Where(e => e.Kind==Kind && StringComparer.Ordinal.Equals(e.Message, Message))];

	// -------------------------
	// Parsing
	// -------------------------

	[GeneratedRegex(@"^Duplicate message received after (?<after>\d+(\.\d+)?) seconds and paused for (?<pause>\d+(\.\d+)?) seconds$", RegexOptions.Compiled)]
	private static partial Regex DupMsgRegex();

	[GeneratedRegex(@"^This message was paused for (?<paused>\d+(\.\d+)?) seconds and was repeated (?<count>\d+)(?<plus>\+1)? times$", RegexOptions.Compiled)]
	private static partial Regex SummaryMsgRegex();

	private static List<LogEvent> ParseEvents(string Content)
	{
		string[] Lines=Content.Replace("\r\n","\n").Split('\n', StringSplitOptions.RemoveEmptyEntries);
		List<LogEvent> Events=[];

		for(int i = 0; i<Lines.Length;) {
			if(i+1<Lines.Length && IsAnnotationLine(Lines[i+1], out string Inner)) {
				string Msg=Lines[i];

				if(DupMsgRegex().Match(Inner) is { Success: true } D) {
					Events.Add(new LogEvent(
						EventKind.Duplicate,
						Msg,
						AfterSeconds: double.Parse(D.Groups["after"].Value, CultureInfo.InvariantCulture),
						PauseSeconds: double.Parse(D.Groups["pause"].Value, CultureInfo.InvariantCulture)
					));
					i+=2;
					continue;
				}

				if(SummaryMsgRegex().Match(Inner) is { Success: true } S) {
					bool Plus=S.Groups["plus"].Success;
					Events.Add(new LogEvent(
						EventKind.Summary,
						Msg,
						PausedSeconds: double.Parse(S.Groups["paused"].Value, CultureInfo.InvariantCulture),
						RepeatedCount: int.Parse(S.Groups["count"].Value, CultureInfo.InvariantCulture)+(Plus ? 1 : 0),
						PlusOne: Plus
					));
					i+=2;
					continue;
				}
			}

			Events.Add(new LogEvent(EventKind.Plain, Lines[i]));
			i++;
		}

		return Events;
	}

	private static bool IsAnnotationLine(string Line, out string Inner)
	{
		if(Line.StartsWith("***", StringComparison.Ordinal) && Line.EndsWith("***", StringComparison.Ordinal)) {
			Inner=Line[3..^3];
			return true;
		}
		Inner="";
		return false;
	}

	// -------------------------
	// Helpers
	// -------------------------

	private static string CreateEmptyTempFile()
	{
		string PathName=Path.GetTempFileName();
		File.WriteAllText(PathName, string.Empty);
		return PathName;
	}
}