//Test code originally generated by ChatGPT, but I ended up rewriting the entire thing
using System.Text;
using DevStrings = SilkDev.DevStrings;

namespace UnitTests;

//Note: Tests assume unicode characters are all valid in the original Str/UTF8Bytes
public sealed class UTF8CutTests
{
	private static readonly Encoding UTF8=Encoding.UTF8;

	//Local links to the functions
	private static class U
	{
		public static string UTF8Cut (string Str		, int MaxByteSize, string AppendOnOverrun) => DevStrings.UTF8Cut (Str		, MaxByteSize, AppendOnOverrun);
		public static string UTF8Cut (byte[] UTF8Bytes	, int MaxByteSize, string AppendOnOverrun) => DevStrings.UTF8Cut (UTF8Bytes	, MaxByteSize, AppendOnOverrun);
		public static byte[] UTF8CutB(string Str		, int MaxByteSize, string AppendOnOverrun) => DevStrings.UTF8CutB(Str		, MaxByteSize, AppendOnOverrun);
		public static byte[] UTF8CutB(byte[] UTF8Bytes	, int MaxByteSize, string AppendOnOverrun) => DevStrings.UTF8CutB(UTF8Bytes	, MaxByteSize, AppendOnOverrun);
	}

	private static void AssertValidUtf8(byte[] Bytes) =>
		Assert.Equal(Bytes, UTF8.GetBytes(UTF8.GetString(Bytes)));

	private static void AssertCutResultString(string Original, string Result, int MaxByteSize, string AppendOnOverrun, bool RefEquals=false)
	{
		if(RefEquals)
			Assert.Same(Original, Result);
		else if(MaxByteSize<=0)
			Assert.Empty(Result);
		else
			AssertCutResultBytes(UTF8.GetBytes(Original), UTF8.GetBytes(Result), MaxByteSize, AppendOnOverrun);
	}

	private static byte[] StripTrailingReplacementChar(byte[] Bytes)
	{
		string Str=UTF8.GetString(Bytes);
		return Bytes.Length>0 && Str[^1]==0xFFFD ? UTF8.GetBytes(Str[..^1]) : Bytes;
	}

	private static void AssertCutResultBytes(byte[] OriginalBytes, byte[] ResultBytes, int MaxByteSize, string AppendOnOverrun, bool RefEquals=false)
	{
		Assert.True(ResultBytes.Length <= Math.Max(MaxByteSize, 0), $"Length check failed: {ResultBytes.Length}>{MaxByteSize}");
		AssertValidUtf8(ResultBytes);
		byte[] AppendBytes;
		if(RefEquals)
			Assert.Same(OriginalBytes, ResultBytes);
		else if(MaxByteSize<=0)
			Assert.Empty(ResultBytes);
		else if(OriginalBytes.Length<=MaxByteSize)
			Assert.Equal(OriginalBytes, ResultBytes);
		else if((AppendBytes=UTF8.GetBytes(AppendOnOverrun)).Length>MaxByteSize)
			Assert.Equal(StripTrailingReplacementChar(AppendBytes[..MaxByteSize]), ResultBytes);
		else
			Assert.Equal([.. StripTrailingReplacementChar(OriginalBytes[..(MaxByteSize-AppendBytes.Length)]).AsEnumerable().Concat(AppendBytes)], ResultBytes);
	}

	public enum CutVariant
	{
		String_To_String,
		Bytes_To_String	,
		String_To_Bytes	,
		Bytes_To_Bytes	,
	}

	public static IEnumerable<object[]> Test_Cases()
	{
		object[][] AllTests=[
			//Empty or <=0 length
			["ABC"	, "xyz"	, 0 ,""		, 0],
			[""		, "xyz"	, 0 ,""		, 1],
			["ABC"	, "xyz"	, -1,""		, 0],
			[""		, "xyz"	, -1,""		, 1],
			[""		, "xyz"	, 1 ,""		, 1],

			//Base ascii tests
			["ABCDE", "xyz"	, 6, "ABCDE", 1], //+1 extra room
			["ABCDE", "xyz"	, 5, "ABCDE", 1], //Exact fit
			["ABCDE", "xyz"	, 4, "Axyz"	, 0], //End=1
			["ABCDE", "xyz"	, 3, "xyz"	, 0], //Suffix-only fits exactly
			["ABCDE", "xyz"	, 2, "xy"	, 0], //Suffix truncated
			["ABCDE", "xyz"	, 1, "x"	, 0], //Suffix truncated

			//4 byte character
			["A😀Br", "xyz"	, 8, "A😀Br", 1],
			["A😀Br", "xyz"	, 7, "A😀Br", 1],
			["A😀Br", "xyz"	, 6, "Axyz"	, 0],
			["😀ABr", "xy"	, 6, "😀xy"	, 0],
			["😀ABr", "x"	, 6, "😀Ax"	, 0],
			["A😀Br", "xyz"	, 5, "Axyz"	, 0],
			["😀ABr", "xyz"	, 5, "xyz"	, 0],
			["😀ABr", "xy"	, 5, "xy"	, 0],
			["😀ABr", "x"	, 5, "😀x"	, 0],
			["😀ABr", ""	, 5, "😀A"	, 0],
			["A😀Br", "xyz"	, 4, "Axyz"	, 0],
			["😀ABr", "xyz"	, 4, "xyz"	, 0],
			["A😀Br", "xyz"	, 3, "xyz"	, 0],
			["A😀Br", "xyz"	, 2, "xy"	, 0],
			["A😀Br", "xyz"	, 1, "x"	, 0],

			//3 byte character
			["A€B"	, "xyz"	, 6, "A€B"	, 1],
			["A€B"	, "xyz"	, 5, "A€B"	, 1],
			["A€B"	, "xy"	, 4, "Axy"	, 0],
			["€AB"	, "xy"	, 4, "xy"	, 0],
			["€AB"	, "x"	, 4, "€x"	, 0],
			["€AB"	, ""	, 4, "€A"	, 0],
			["A€B"	, "xyz"	, 3, "xyz"	, 0],
			["€AB"	, "xyz"	, 3, "xyz"	, 0],

			//2 byte character
			["A©B"	, "xyz"	, 5, "A©B"	, 1],
			["A©B"	, "xy"	, 4, "A©B"	, 1],
			["A©B"	, "xyz"	, 3, "xyz"	, 0],
			["©AB"	, "xy"	, 3, "xy"	, 0],
			["©AB"	, "x"	, 3, "©x"	, 0],
			["A©B"	, ""	, 3, "A©"	, 0],
			["A©B"	, "xyz"	, 2, "xy"	, 0],

			//1 byte character
			["AB"	, "xy"	, 3, "AB"	, 1],
			["AB"	, "xyz"	, 2, "AB"	, 1],
			["AB"	, "xyz"	, 1, "x"	, 0],
			["AB"	, "x"	, 1, "x"	, 0],
			["AB"	, ""	, 1, "A"	, 0],

			//Non-ASCII AppendOnOverrun
			["ABCDE", "🔥"	, 5, "ABCDE", 1], //🔥 is 4 bytes
			["ABCDEF","🔥"	, 5, "A🔥"	, 0],
			["ABCDE", "🔥"	, 4, "🔥"	, 0],
			["ABCDE", "🔥"	, 3, ""		, 0],
			["ABCDE", "©"	, 6, "ABCDE", 1], //© is 2 bytes
			["ABCDE", "©"	, 1, ""		, 0],
			["ABCDE", "©"	, 2, "©"	, 0],
			["ABCDE", "©"	, 3, "A©"	, 0],
			["ABCDE", "…"	, 2, ""		, 0], //… is 3 bytes
			["ABCDE", "…"	, 3, "…"	, 0],
			["ABCDE", "…"	, 4, "A…"	, 0],

			//A few more split character tests
			["A©B"	, "x"	, 3, "Ax"	, 0],
			["A€B"	, "x"	, 4, "Ax"	, 0],
			["A😀B"	, "x"	, 5, "Ax"	, 0],
		];
		foreach(object[] Tests in AllTests)
			yield return Tests;
	}

	public static IEnumerable<object[]> Test_Cases_With_Variants()
	{
		foreach(CutVariant V in new[] { CutVariant.String_To_String, CutVariant.Bytes_To_String, CutVariant.String_To_Bytes, CutVariant.Bytes_To_Bytes })
			foreach(object[] Row in Test_Cases())
				yield return [ V, ..Row ];
	}

	[Theory]
	[MemberData(nameof(Test_Cases_With_Variants))]
	public void Cutting_All_Variants(CutVariant Variant, string Str, string Append, int Max, string Expected, int RefMatch)
	{
		byte[] StartBytes=UTF8.GetBytes(Str);
		bool ToString =(Variant is CutVariant.String_To_String or CutVariant.Bytes_To_String);
		bool SameTypes=(Variant is CutVariant.String_To_String or CutVariant.Bytes_To_Bytes );
		bool RefEquals=SameTypes && StartBytes.Length<=Max;

		object Result=Variant switch {
			CutVariant.String_To_String	=> U.UTF8Cut (Str		, Max, Append),
			CutVariant.Bytes_To_String	=> U.UTF8Cut (StartBytes, Max, Append),
			CutVariant.String_To_Bytes	=> U.UTF8CutB(Str		, Max, Append),
			CutVariant.Bytes_To_Bytes	=> U.UTF8CutB(StartBytes, Max, Append),
			_ => throw new NotImplementedException(),
		};

		Assert.True((RefMatch==1 && (SameTypes || Str.Length==0))==ReferenceEquals(ToString ? Str : StartBytes, Result), "Equal Reference mismatch");
		Assert.Equal(Expected, ToString ? (string)Result : UTF8.GetString((byte[])Result));
		if(ToString)
			AssertCutResultString(Str		, (string)Result, Max, Append, RefEquals);
		else
			AssertCutResultBytes (StartBytes, (byte[])Result, Max, Append, RefEquals);
	}
}